version: '3.9'

services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0"
    ports: 
      - 8000:8000
    volumes:
      - ./app/backend:/etc/backend
    depends_on:
      - db

  frontend:
    build: 
      context: ./app/frontend 
      dockerfile: Dockerfile
    
    command: "yarn dev"
    
    ports:
      - 3000:3000
    
    volumes:
      - ./app/frontend:/etc/app
      - /etc/app/node_modules
    

  db:
    image: postgres
    restart: always
    env_file:
      - ./app/backend/.env
    volumes:
      - dummy_db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  dummy_db:

